version: '2'
services:
  db:
    image: mariadb:10.1
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: kucrut/wordpress
    depends_on:
      - db
    volumes:
      - "./data/content:/var/www/content"
      - "./config/wordpress:/var/www/wp-configs"
      - "./log/nginx:/var/log/nginx"
      - "./log/php7:/var/log/php7"
    links:
      - db
    ports:
      - "80:80"
    env_file: env.dev
